
# Server configuration for unit tests - do not use for production!
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

#Set max connections to 1 to make it easy to find connection leaks
jerseyClientConfiguration:
  maxConnections: 1
  timeout: 1000 ms
  connectionTimeout: 1000 ms
