
# Server configuration for unit tests - do not use for production!
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081


jerseyClientConfiguration:
  maxConnections: 1 # with a connection pool of 1, it's quicker to find any leaks
  timeout: 2000 ms # sometimes my ISP is very slow
  connectionTimeout: 2000 ms #sometimes my ISP is very slow
