
# Default server configuration for deployed environments
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081


jerseyClientConfiguration:
  timeout: 2000 ms # sometimes my ISP is very slow
  connectionTimeout: 2000 ms # sometimes my ISP is very slow